package lt.nsg.jdbcglass;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.*;

public class ConnectionProxy extends AbstractConnectionProxy {
    private final Logger log = LoggerFactory.getLogger(ConnectionProxy.class);

    public ConnectionProxy(Connection connection) {
        super(connection);
        log.info("Connection opened");
    }

    @Override
    public void close() throws SQLException {
        getConnection().close();
        log.info("Connection closed");
    }

    @Override
    public Statement createStatement() throws SQLException {
        return proxyStatement(getConnection().createStatement());
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        Statement statement = getConnection().createStatement(resultSetType, resultSetConcurrency);
        return proxyStatement(statement);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        Statement statement = getConnection().createStatement(resultSetType, resultSetConcurrency, resultSetHoldability);
        return proxyStatement(statement);
    }

    private Statement proxyStatement(Statement statement) throws SQLException {
        return new StatementProxy(statement, this);
    }

    @Override
    public void setAutoCommit(boolean autoCommit) throws SQLException {
        boolean previousAutoCommit = getCurrentAutoCommit();
        getConnection().setAutoCommit(autoCommit);
        if (previousAutoCommit && !autoCommit) {
            log.info("Transaction committed");
        } else if (!previousAutoCommit && autoCommit) {
            log.info("Transaction started");
        }
    }

    @Override
    public void rollback() throws SQLException {
        getConnection().rollback();
        log.info("Transaction rolledback");
    }

    @Override
    public void rollback(Savepoint savepoint) throws SQLException {
        getConnection().rollback(savepoint);
        log.info("Transaction rolledback");
    }

    private boolean getCurrentAutoCommit() throws SQLException {
        return getConnection().getAutoCommit();
    }

    @Override
    public void commit() throws SQLException {
        getConnection().commit();
        log.info("Transaction committed");
    }

    @Override
    public DatabaseMetaData getMetaData() throws SQLException {
        DatabaseMetaData metaData = getConnection().getMetaData();
        return new DatabaseMetaDataProxy(metaData, this);
    }

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException {
        CallableStatement statement = getConnection().prepareCall(sql);
        return proxyCallableStatement(statement);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        CallableStatement statement = getConnection().prepareCall(sql, resultSetType, resultSetConcurrency);
        return proxyCallableStatement(statement);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        CallableStatement statement = getConnection().prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
        return proxyCallableStatement(statement);
    }

    public PreparedStatement prepareStatement(String sql) throws SQLException {
        PreparedStatement statement = getConnection().prepareStatement(sql);
        return proxyPreparedStatement(statement);
    }

    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        PreparedStatement statement = getConnection().prepareStatement(sql, resultSetType, resultSetConcurrency);
        return proxyPreparedStatement(statement);
    }

    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        PreparedStatement statement = getConnection().prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
        return proxyPreparedStatement(statement);
    }

    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        PreparedStatement statement = getConnection().prepareStatement(sql, autoGeneratedKeys);
        return proxyPreparedStatement(statement);
    }

    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        PreparedStatement statement = getConnection().prepareStatement(sql, columnIndexes);
        return proxyPreparedStatement(statement);
    }

    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        PreparedStatement statement = getConnection().prepareStatement(sql, columnNames);
        return proxyPreparedStatement(statement);
    }

    private CallableStatement proxyCallableStatement(CallableStatement statement) {
        return new CallableStatementProxy(statement, this);
    }

    private PreparedStatement proxyPreparedStatement(PreparedStatement statement) {
        return new PreparedStatementProxy(statement, this);
    }
}

