package lt.nsg.jdbcglass.statement;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class StatementProxy extends AbstractStatementProxy {
    private final static Logger log = LoggerFactory.getLogger(StatementProxy.class);
    private final StatementHelper statementHelper;

    public StatementProxy(Statement statement, Connection connection) {
        super(statement, connection);
        this.statementHelper = new StatementHelper();
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        int rows = super.executeUpdate(sql);
        statementHelper.logSql(sql, log);
        return rows;
    }


    @Override
    public boolean execute(String sql) throws SQLException {
        boolean result = super.execute(sql);
        statementHelper.logSql(sql, log);
        return result;
    }

    @Override
    public void addBatch(String sql) throws SQLException {
        super.addBatch(sql);
        statementHelper.addBatch(sql);
    }

    @Override
    public void clearBatch() throws SQLException {
        super.clearBatch();
        statementHelper.clearBatches();
    }

    @Override
    public int[] executeBatch() throws SQLException {
        int[] rows = super.executeBatch();
        statementHelper.logBatch(log);
        statementHelper.clearBatches();
        return rows;
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        int rows = super.executeUpdate(sql, autoGeneratedKeys);
        statementHelper.logSql(sql, log);
        return rows;
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        int rows = super.executeUpdate(sql, columnIndexes);
        statementHelper.logSql(sql, log);
        return rows;
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        int rows = super.executeUpdate(sql, columnNames);
        statementHelper.logSql(sql, log);
        return rows;
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        boolean result = super.execute(sql, autoGeneratedKeys);
        statementHelper.logSql(sql, log);
        return result;
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        boolean result = super.execute(sql, columnIndexes);
        statementHelper.logSql(sql, log);
        return result;
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        boolean result = super.execute(sql, columnNames);
        statementHelper.logSql(sql, log);
        return result;
    }


    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        ResultSet resultSet = super.executeQuery(sql);
        statementHelper.logSql(sql, log);
        return resultSet;
    }

    protected StatementHelper getStatementHelper() {
        return this.statementHelper;
    }
}